"""initial schema

Revision ID: b6e6ad18fdcc
Revises:
Create Date: 2026-07-23 06:51:57.991855+00:00
"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "b6e6ad18fdcc"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crawl_attempts",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "attempted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("url_id", sa.BigInteger(), nullable=False),
        sa.Column("crawl_job_id", sa.Uuid(), nullable=True),
        sa.Column("worker_id", sa.String(length=200), nullable=True),
        sa.Column(
            "fetch_method",
            sa.Enum("http", "browser", name="fetchmethod", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "outcome",
            sa.Enum(
                "success",
                "not_modified",
                "failed",
                "blocked",
                "skipped",
                name="attemptoutcome",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("bytes_downloaded", sa.BigInteger(), nullable=True),
        sa.Column(
            "failure_category",
            sa.Enum(
                "dns_failure",
                "connection_timeout",
                "http_403",
                "http_429",
                "http_5xx",
                "http_other",
                "robots_restricted",
                "parser_failure",
                "browser_failure",
                "database_failure",
                "llm_failure",
                "embedding_failure",
                "unknown",
                name="failurecategory",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", "attempted_at", name=op.f("pk_crawl_attempts")),
        postgresql_partition_by="RANGE (attempted_at)",
    )
    op.create_index(
        op.f("ix_crawl_attempts_crawl_job_id"), "crawl_attempts", ["crawl_job_id"], unique=False
    )
    op.create_index(op.f("ix_crawl_attempts_url_id"), "crawl_attempts", ["url_id"], unique=False)
    op.create_table(
        "crawl_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("crawl_job_id", sa.Uuid(), nullable=True),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("url_id", sa.BigInteger(), nullable=True),
        sa.Column("worker_id", sa.String(length=200), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id", "created_at", name=op.f("pk_crawl_events")),
        postgresql_partition_by="RANGE (created_at)",
    )
    op.create_index(
        op.f("ix_crawl_events_crawl_job_id"), "crawl_events", ["crawl_job_id"], unique=False
    )
    op.create_index(
        op.f("ix_crawl_events_event_type"), "crawl_events", ["event_type"], unique=False
    )
    op.create_table(
        "crawl_workers",
        sa.Column("id", sa.String(length=200), nullable=False),
        sa.Column(
            "worker_type",
            sa.Enum("crawler", "processor", name="workertype", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "starting",
                "running",
                "draining",
                "stopped",
                name="workerstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("hostname", sa.String(length=200), nullable=False),
        sa.Column("pid", sa.Integer(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_heartbeat_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("current_job_id", sa.Uuid(), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crawl_workers")),
    )
    op.create_index(
        op.f("ix_crawl_workers_last_heartbeat_at"),
        "crawl_workers",
        ["last_heartbeat_at"],
        unique=False,
    )
    op.create_table(
        "entities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("normalized_name", sa.String(length=500), nullable=False),
        sa.Column(
            "entity_type",
            sa.Enum(
                "person",
                "organization",
                "location",
                "event",
                "other",
                name="entitytype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entities")),
        sa.UniqueConstraint(
            "normalized_name", "entity_type", name=op.f("uq_entities_normalized_name")
        ),
    )
    op.create_table(
        "processing_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "stage",
            sa.Enum(
                "cleaning",
                "llm_extraction",
                "embedding",
                name="processingstage",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "completed",
                "failed",
                "dead_letter",
                name="processingstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("article_id", sa.Uuid(), nullable=True),
        sa.Column("url_id", sa.BigInteger(), nullable=True),
        sa.Column("message_id", sa.String(length=100), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "enqueued_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_processing_jobs")),
    )
    op.create_index(
        op.f("ix_processing_jobs_article_id"), "processing_jobs", ["article_id"], unique=False
    )
    op.create_index(
        "ix_processing_jobs_stage_status", "processing_jobs", ["stage", "status"], unique=False
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("base_url", sa.String(length=500), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("country", sa.String(length=8), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("crawl_enabled", sa.Boolean(), nullable=False),
        sa.Column("allowed_domains", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("article_url_patterns", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("section_urls", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sitemap_urls", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rss_urls", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("crawl_frequency_minutes", sa.Integer(), nullable=False),
        sa.Column("rate_limit_delay_seconds", sa.Float(), nullable=False),
        sa.Column("max_concurrency", sa.Integer(), nullable=False),
        sa.Column("requires_browser", sa.Boolean(), nullable=False),
        sa.Column("extraction_strategy", sa.String(length=50), nullable=False),
        sa.Column("robots_policy", sa.String(length=20), nullable=False),
        sa.Column("source_weight", sa.Float(), nullable=False),
        sa.Column("url_normalization", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("last_successful_crawl_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
    )
    op.create_index(op.f("ix_sources_slug"), "sources", ["slug"], unique=True)
    op.create_table(
        "system_metrics",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("metric_name", sa.String(length=200), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("labels", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_system_metrics")),
    )
    op.create_index(
        "ix_system_metrics_name_time",
        "system_metrics",
        ["metric_name", "recorded_at"],
        unique=False,
    )
    op.create_table(
        "topics",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_topics")),
        sa.UniqueConstraint("slug", name=op.f("uq_topics_slug")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=200), nullable=False),
        sa.Column(
            "role",
            sa.Enum("admin", "viewer", name="userrole", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "articles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("url_id", sa.BigInteger(), nullable=True),
        sa.Column("canonical_url", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("subtitle", sa.Text(), nullable=True),
        sa.Column("author", sa.String(length=500), nullable=True),
        sa.Column("category", sa.String(length=200), nullable=True),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("country", sa.String(length=8), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at_source", sa.DateTime(timezone=True), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("image_urls", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("raw_html_location", sa.String(length=500), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("simhash", sa.BigInteger(), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column(
            "extraction_method",
            sa.Enum(
                "selectors",
                "json_ld",
                "opengraph",
                "readability",
                "llm",
                name="extractionmethod",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("extraction_confidence", sa.Float(), nullable=False),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column("sentiment", sa.String(length=20), nullable=True),
        sa.Column("event_type", sa.String(length=100), nullable=True),
        sa.Column("political_category", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("fk_articles_source_id_sources")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_articles")),
        sa.UniqueConstraint("canonical_url", name=op.f("uq_articles_canonical_url")),
    )
    op.create_index(op.f("ix_articles_content_hash"), "articles", ["content_hash"], unique=False)
    op.create_index("ix_articles_language", "articles", ["language"], unique=False)
    op.create_index("ix_articles_published_at", "articles", ["published_at"], unique=False)
    op.create_index(op.f("ix_articles_simhash"), "articles", ["simhash"], unique=False)
    op.create_index(
        "ix_articles_source_published", "articles", ["source_id", "published_at"], unique=False
    )
    op.create_index(op.f("ix_articles_url_id"), "articles", ["url_id"], unique=False)
    op.create_table(
        "crawl_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column(
            "job_type",
            sa.Enum(
                "full_crawl",
                "incremental_crawl",
                "section_crawl",
                "url_crawl",
                "retry_failed",
                "backfill",
                name="crawljobtype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "created",
                "queued",
                "running",
                "paused",
                "completed",
                "failed",
                "cancelled",
                name="crawljobstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pages_discovered", sa.Integer(), nullable=False),
        sa.Column("pages_requested", sa.Integer(), nullable=False),
        sa.Column("pages_successful", sa.Integer(), nullable=False),
        sa.Column("pages_failed", sa.Integer(), nullable=False),
        sa.Column("pages_skipped", sa.Integer(), nullable=False),
        sa.Column("pages_changed", sa.Integer(), nullable=False),
        sa.Column("pages_unchanged", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_crawl_jobs_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("fk_crawl_jobs_source_id_sources")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crawl_jobs")),
    )
    op.create_index(op.f("ix_crawl_jobs_source_id"), "crawl_jobs", ["source_id"], unique=False)
    op.create_index(
        "ix_crawl_jobs_source_status", "crawl_jobs", ["source_id", "status"], unique=False
    )
    op.create_index(op.f("ix_crawl_jobs_status"), "crawl_jobs", ["status"], unique=False)
    op.create_table(
        "crawl_urls",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=True),
        sa.Column("normalized_url", sa.Text(), nullable=False),
        sa.Column("url_hash", sa.String(length=64), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("discovered_from", sa.Text(), nullable=True),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Float(), nullable=False),
        sa.Column(
            "url_type",
            sa.Enum(
                "homepage",
                "section",
                "article",
                "sitemap",
                "rss",
                "other",
                name="urltype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "discovered",
                "queued",
                "leased",
                "crawling",
                "success",
                "failed",
                "retry_pending",
                "blocked",
                "skipped",
                name="urlstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_crawled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "next_crawl_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("last_http_status", sa.Integer(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "failure_category",
            sa.Enum(
                "dns_failure",
                "connection_timeout",
                "http_403",
                "http_429",
                "http_5xx",
                "http_other",
                "robots_restricted",
                "parser_failure",
                "browser_failure",
                "database_failure",
                "llm_failure",
                "embedding_failure",
                "unknown",
                name="failurecategory",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("etag", sa.String(length=500), nullable=True),
        sa.Column("last_modified", sa.String(length=100), nullable=True),
        sa.Column("lease_owner", sa.String(length=200), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("crawl_job_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("fk_crawl_urls_source_id_sources")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crawl_urls")),
        sa.UniqueConstraint("url_hash", name=op.f("uq_crawl_urls_url_hash")),
    )
    op.create_index(
        "ix_crawl_urls_claim",
        "crawl_urls",
        ["source_id", "next_crawl_at"],
        unique=False,
        postgresql_where=sa.text("status IN ('queued', 'retry_pending')"),
    )
    op.create_index("ix_crawl_urls_content_hash", "crawl_urls", ["content_hash"], unique=False)
    op.create_index(
        "ix_crawl_urls_domain_next", "crawl_urls", ["domain", "next_crawl_at"], unique=False
    )
    op.create_index(
        "ix_crawl_urls_lease_expiry",
        "crawl_urls",
        ["lease_expires_at"],
        unique=False,
        postgresql_where=sa.text("status IN ('leased', 'crawling')"),
    )
    op.create_index(
        "ix_crawl_urls_source_status", "crawl_urls", ["source_id", "status"], unique=False
    )
    op.create_table(
        "article_embeddings",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("article_id", sa.Uuid(), nullable=False),
        sa.Column(
            "embedding_kind",
            sa.Enum(
                "title",
                "summary",
                "body",
                "entity",
                name="embeddingkind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("embedding_model", sa.String(length=200), nullable=False),
        sa.Column("embedding_dimension", sa.Integer(), nullable=False),
        sa.Column("embedding_version", sa.Integer(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["article_id"], ["articles.id"], name=op.f("fk_article_embeddings_article_id_articles")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_article_embeddings")),
        sa.UniqueConstraint(
            "article_id",
            "embedding_kind",
            "embedding_model",
            "embedding_version",
            name=op.f("uq_article_embeddings_article_id"),
        ),
    )
    op.create_index(
        op.f("ix_article_embeddings_article_id"), "article_embeddings", ["article_id"], unique=False
    )
    op.create_table(
        "article_entities",
        sa.Column("article_id", sa.Uuid(), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("mention_count", sa.Integer(), nullable=False),
        sa.Column("salience", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["article_id"], ["articles.id"], name=op.f("fk_article_entities_article_id_articles")
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["entities.id"], name=op.f("fk_article_entities_entity_id_entities")
        ),
        sa.PrimaryKeyConstraint("article_id", "entity_id", name=op.f("pk_article_entities")),
    )
    op.create_index(
        op.f("ix_article_entities_entity_id"), "article_entities", ["entity_id"], unique=False
    )
    op.create_table(
        "article_topics",
        sa.Column("article_id", sa.Uuid(), nullable=False),
        sa.Column("topic_id", sa.Uuid(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["article_id"], ["articles.id"], name=op.f("fk_article_topics_article_id_articles")
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"], ["topics.id"], name=op.f("fk_article_topics_topic_id_topics")
        ),
        sa.PrimaryKeyConstraint("article_id", "topic_id", name=op.f("pk_article_topics")),
    )
    op.create_index(
        op.f("ix_article_topics_topic_id"), "article_topics", ["topic_id"], unique=False
    )
    op.create_table(
        "article_versions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("article_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("subtitle", sa.Text(), nullable=True),
        sa.Column("author", sa.String(length=500), nullable=True),
        sa.Column("category", sa.String(length=200), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("title_changed", sa.Boolean(), nullable=False),
        sa.Column("body_changed", sa.Boolean(), nullable=False),
        sa.Column("author_changed", sa.Boolean(), nullable=False),
        sa.Column("published_at_changed", sa.Boolean(), nullable=False),
        sa.Column("category_changed", sa.Boolean(), nullable=False),
        sa.Column("metadata_changed", sa.Boolean(), nullable=False),
        sa.Column(
            "detected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["article_id"], ["articles.id"], name=op.f("fk_article_versions_article_id_articles")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_article_versions")),
        sa.UniqueConstraint("article_id", "version", name=op.f("uq_article_versions_article_id")),
    )
    op.create_index(
        op.f("ix_article_versions_article_id"), "article_versions", ["article_id"], unique=False
    )
    op.create_table(
        "llm_extractions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("article_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "completed",
                "failed",
                "dead_letter",
                name="processingstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("extraction", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["article_id"], ["articles.id"], name=op.f("fk_llm_extractions_article_id_articles")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_extractions")),
    )
    op.create_index(
        op.f("ix_llm_extractions_article_id"), "llm_extractions", ["article_id"], unique=False
    )
    # ### end Alembic commands ###

    # ── Manual DDL ────────────────────────────────────────────────────────────

    # Partition management: monthly range partitions for the append-only,
    # high-volume tables. `ensure_monthly_partitions` is idempotent and is also
    # invoked by workers at startup so future months always exist; the DEFAULT
    # partition is a safety net against writes racing partition creation.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION ensure_monthly_partitions(
            parent_table text,
            partition_column text,
            months_ahead int DEFAULT 2
        ) RETURNS void AS $$
        DECLARE
            month_start date;
            month_end date;
            partition_name text;
            i int;
        BEGIN
            FOR i IN 0..months_ahead LOOP
                month_start := date_trunc('month', now())::date + (i || ' months')::interval;
                month_end := month_start + interval '1 month';
                partition_name := parent_table || '_p_'
                    || to_char(month_start, 'YYYY') || 'm' || to_char(month_start, 'MM');
                EXECUTE format(
                    'CREATE TABLE IF NOT EXISTS %I PARTITION OF %I FOR VALUES FROM (%L) TO (%L)',
                    partition_name, parent_table, month_start, month_end
                );
            END LOOP;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        "CREATE TABLE IF NOT EXISTS crawl_attempts_p_default PARTITION OF crawl_attempts DEFAULT"
    )
    op.execute(
        "CREATE TABLE IF NOT EXISTS crawl_events_p_default PARTITION OF crawl_events DEFAULT"
    )
    op.execute("SELECT ensure_monthly_partitions('crawl_attempts', 'attempted_at', 2)")
    op.execute("SELECT ensure_monthly_partitions('crawl_events', 'created_at', 2)")

    # Vector similarity: HNSW cosine index (builds incrementally, unlike IVFFlat
    # which needs data present at build time).
    op.execute(
        "CREATE INDEX ix_article_embeddings_hnsw ON article_embeddings"
        " USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64)"
    )

    # Keyword search over titles (works for Bangla and English strings alike).
    op.execute("CREATE INDEX ix_articles_title_trgm ON articles USING gin (title gin_trgm_ops)")


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_articles_title_trgm")
    op.execute("DROP INDEX IF EXISTS ix_article_embeddings_hnsw")
    op.execute("DROP FUNCTION IF EXISTS ensure_monthly_partitions(text, text, int)")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_llm_extractions_article_id"), table_name="llm_extractions")
    op.drop_table("llm_extractions")
    op.drop_index(op.f("ix_article_versions_article_id"), table_name="article_versions")
    op.drop_table("article_versions")
    op.drop_index(op.f("ix_article_topics_topic_id"), table_name="article_topics")
    op.drop_table("article_topics")
    op.drop_index(op.f("ix_article_entities_entity_id"), table_name="article_entities")
    op.drop_table("article_entities")
    op.drop_index(op.f("ix_article_embeddings_article_id"), table_name="article_embeddings")
    op.drop_table("article_embeddings")
    op.drop_index("ix_crawl_urls_source_status", table_name="crawl_urls")
    op.drop_index(
        "ix_crawl_urls_lease_expiry",
        table_name="crawl_urls",
        postgresql_where=sa.text("status IN ('leased', 'crawling')"),
    )
    op.drop_index("ix_crawl_urls_domain_next", table_name="crawl_urls")
    op.drop_index("ix_crawl_urls_content_hash", table_name="crawl_urls")
    op.drop_index(
        "ix_crawl_urls_claim",
        table_name="crawl_urls",
        postgresql_where=sa.text("status IN ('queued', 'retry_pending')"),
    )
    op.drop_table("crawl_urls")
    op.drop_index(op.f("ix_crawl_jobs_status"), table_name="crawl_jobs")
    op.drop_index("ix_crawl_jobs_source_status", table_name="crawl_jobs")
    op.drop_index(op.f("ix_crawl_jobs_source_id"), table_name="crawl_jobs")
    op.drop_table("crawl_jobs")
    op.drop_index(op.f("ix_articles_url_id"), table_name="articles")
    op.drop_index("ix_articles_source_published", table_name="articles")
    op.drop_index(op.f("ix_articles_simhash"), table_name="articles")
    op.drop_index("ix_articles_published_at", table_name="articles")
    op.drop_index("ix_articles_language", table_name="articles")
    op.drop_index(op.f("ix_articles_content_hash"), table_name="articles")
    op.drop_table("articles")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("topics")
    op.drop_index("ix_system_metrics_name_time", table_name="system_metrics")
    op.drop_table("system_metrics")
    op.drop_index(op.f("ix_sources_slug"), table_name="sources")
    op.drop_table("sources")
    op.drop_index("ix_processing_jobs_stage_status", table_name="processing_jobs")
    op.drop_index(op.f("ix_processing_jobs_article_id"), table_name="processing_jobs")
    op.drop_table("processing_jobs")
    op.drop_table("entities")
    op.drop_index(op.f("ix_crawl_workers_last_heartbeat_at"), table_name="crawl_workers")
    op.drop_table("crawl_workers")
    op.drop_index(op.f("ix_crawl_events_event_type"), table_name="crawl_events")
    op.drop_index(op.f("ix_crawl_events_crawl_job_id"), table_name="crawl_events")
    op.drop_table("crawl_events")
    op.drop_index(op.f("ix_crawl_attempts_url_id"), table_name="crawl_attempts")
    op.drop_index(op.f("ix_crawl_attempts_crawl_job_id"), table_name="crawl_attempts")
    op.drop_table("crawl_attempts")
    # ### end Alembic commands ###
